service: ops-bot-merger

provider:
  name: aws
  region: us-east-2
  timeout: 30
  memorySize: 1024
  stage: dev
  runtime: nodejs12.x
  logRetentionInDays: 60

functions:
  handleProbot:
    handler: dist/main.mergePRs
    events:
      - schedule: rate(15 minutes)
    environment:
      LOG_LEVEL: debug
      APP_ID: ${env:APP_ID}
      PRIVATE_KEY: ${env:PRIVATE_KEY}
