name: Deploy Auto-Merger

on:
  push:
    branches: main
    paths:
      - "auto-merger/src/**"
      - "auto-merger/package*.json"
      - "auto-merger/serverless.yaml"

defaults:
  run:
    working-directory: auto-merger

jobs:
  deploy:
    name: Deploy auto-merger
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm ci
      - name: Test auto-merger
        run: npm run test
      - name: Build auto-merger
        run: npm run build
      - name: Deploy Probot
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
